// <auto-generated />
using System;
using ActividadDeportiva.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActividadDeportiva.Infrastructure.Migrations
{
    [DbContext(typeof(ActividadDeportivaContext))]
    [Migration("20250720201249_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActividadDeportiva.Domain.Entities.UsuarioDeportivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AlturaCm")
                        .HasColumnType("float");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PesoKg")
                        .HasColumnType("float");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlturaCm = 160.0,
                            Apellido = "Batista",
                            Correo = "Franche.fit@gmail.com",
                            FechaNacimiento = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenina",
                            Nombre = "Franchelys",
                            PesoKg = 40.0,
                            Telefono = "809-418-2018"
                        },
                        new
                        {
                            Id = 2,
                            AlturaCm = 185.0,
                            Apellido = "Batista",
                            Correo = "Frank.entrenamiento@gmail.com",
                            FechaNacimiento = new DateTime(1988, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            Nombre = "Frankjerson",
                            PesoKg = 78.0,
                            Telefono = "829-999-6088"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
